# secrets.toml template for API credentials

GOOGLE_SPEECH_API_KEY = "AIzaSyBa5738-etYo7k09gAc0qEc7KlSzaTkjoc"
GOOGLE_TTS_API_KEY = "AIzaSyBa5738-etYo7k09gAc0qEc7KlSzaTkjoc"
api_key = "d1715812b01a44b3952bf210ebf6cd81"
